# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Roller Coaster/Include/Load3DModel/3DSLoader.h \
    ./Roller Coaster/Include/Utilities/3DUtils.h \
    ./Roller Coaster/Include/Utilities/ArcBallCam.H \
    ./Roller Coaster/Include/ControlPoint.H \
    ./Roller Coaster/Include/Utilities/Pnt3f.H \
    ./Roller Coaster/Include/Load3DModel/TGATexture.h \
    ./Roller Coaster/Include/Track.H \
    ./Roller Coaster/Include/Load3DModel/point3d.h \
    ./Roller Coaster/GeneratedFiles/ui_AppMain.h \
    ./Roller Coaster/Include/Load3DModel/vector.h \
    ./Roller Coaster/Include/AppMain.h \
    ./Roller Coaster/Include/TrainView.h
SOURCES += ./Roller Coaster/Src/Load3DModel/3DSLoader.cpp \
    ./Roller Coaster/Src/Utilities/3DUtils.cpp \
    ./Roller Coaster/Src/AppMain.cpp \
    ./Roller Coaster/Src/Utilities/ArcBallCam.cpp \
    ./Roller Coaster/Src/Load3DModel/CBMPLoader.cpp \
    ./Roller Coaster/Src/ControlPoint.cpp \
    ./Roller Coaster/Src/Load3DModel/Model.cpp \
    ./Roller Coaster/Src/Utilities/Pnt3f.cpp \
    ./Roller Coaster/Src/Load3DModel/TGATexture.cpp \
    ./Roller Coaster/Src/Track.cpp \
    ./Roller Coaster/Src/TrainView.cpp \
    ./Roller Coaster/Src/main.cpp \
    ./Roller Coaster/GeneratedFiles/qrc_AppMain.cpp \
    ./Roller Coaster/Src/Load3DModel/vector.cpp
FORMS += ./Roller Coaster/AppMain.ui
RESOURCES += Roller Coaster/AppMain.qrc
